services:
  - type: web
    name: telegram-leak-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: YOUR_TELEGRAM_ID
        sync: false
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: telegram-leak-bot
          property: url
